manifest:
  remotes:
    - name: zagerx
      url-base: https://github.com/zagerx
  
  projects:
    - name: CommonLibrary
      path: ./apps/CommonLibrary/
      remote: zagerx
      revision: master
